/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.mybatis.spring.boot.mybatis.spring.boot.starter)
    api(libs.org.bgee.log4jdbc.log4j2.log4jdbc.log4j2.jdbc4.v1)
    api(libs.org.apache.logging.log4j.log4j.core)
    api(libs.com.oracle.ojdbc.orai18n)
    runtimeOnly(libs.org.springframework.boot.spring.boot.devtools)
    runtimeOnly(libs.com.microsoft.sqlserver.mssql.jdbc)
    runtimeOnly(libs.com.oracle.database.jdbc.ojdbc11)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.mybatis.spring.boot.mybatis.spring.boot.starter.test)
    compileOnly(libs.org.apache.tomcat.embed.tomcat.embed.jasper)
    compileOnly(libs.javax.servlet.javax.servlet.api)
}

group = "SALE_MNG"
version = "0.0.1-SNAPSHOT"
description = "1774182765834"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

