# Whether use or not(true or false)
# foramt : physical field name = true
# foramt : physical field name = false
SALE_REG_DATE=true
SALE_AMT=true
SALE_SITE=true
SALE_DATE=true
SALE_MANAGER=true
SALE_ITEM=true

